ALTER TABLE trades ADD COLUMN IF NOT EXISTS commission DECIMAL(12, 4) DEFAULT 0;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS swap DECIMAL(12, 4) DEFAULT 0;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS external_id TEXT;
CREATE INDEX IF NOT EXISTS idx_trades_external_id ON trades(external_id);

ALTER TABLE trades ALTER COLUMN stop_loss DROP NOT NULL;
ALTER TABLE trades ALTER COLUMN take_profit DROP NOT NULL;
